openapi: 3.0.1
info:
  title: Swagger Webropay exam documentation
  description: This is the documentation used for Webropay exam application
  termsOfService: http://swagger.io/terms/
  contact:
    email: jhalvesmeira@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:5432
tags:
- name: Webropay API simulation
  description: A simulation of contracts API
  externalDocs:
    description: Find out more
    url: https://webropay.com.br/#sobre
- name: contract
  description: Access and editing of contracts
paths:
  /contracts:
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
      - CORS
      responses:
        200:
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
    get:
      tags:
      - contract
      summary: Get a list of all contracts
      operationId: getContracts
      responses:
        "200":
          description: Successful operation
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contract'
                x-content-type: application/xml
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contract'
        "400":
          description: Wrong request
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
        "405":
          description: Validation exception
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Contract
  /contract/{contractId}:
    put:
      tags:
      - contract
      summary: Edit contract
      operationId: editContract
      parameters:
      - name: contractId
        in: path
        description: ID of the contract to be edited
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Edited contract object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Contract'
        required: true
      responses:
        "200":
          description: Successfull operation
          content: {}
        "400":
          description: Invalid contract id supplied
          content: {}
        "404":
          description: Contract not found
          content: {}
      x-swagger-router-controller: Contract
  /contract:
    post:
      tags:
      - contract
      summary: Adds a contract to the Webropay repository
      operationId: addContract
      requestBody:
        description: order placed for purchasing the pet
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Contract'
        required: true
      responses:
        "200":
          description: successful operation
          content: {}
        "400":
          description: Invalid Order
          content: {}
      x-swagger-router-controller: Contract
components:
  schemas:
    Contract:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        status:
          type: boolean
          description: Contract Status
      example:
        description: description
        id: 0
        status: true
      xml:
        name: Contract
